version: "3.8"
services:
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
  # news_simulator_benzinga:
  #   build:
  #     context: ./news_simulator_benzinga
  #   volumes:
  #     - ./news_simulator_benzinga:/app
  news_simulator_finhub:
    build:
      context: ./news_simulator_finhub
    volumes:
      - ./news_simulator_finhub:/app
  db_writer:
    build:
      context: ./db_writer
    env_file: .env
    depends_on:
      - nats
    volumes:
      - ./db_writer:/app
  summary_service:
    build:
      context: ./summary_service
    env_file: .env
    depends_on:
      - nats
    volumes:
      - ./summary_service:/app
  api_server:
    build:
      context: ./api_server
    env_file: .env
    volumes:
      - ./api_server:/app
    ports:
      - "8000:8000"
  # slack_bot:
  #   build:
  #     context: ./slack_bot
  #   env_file: .env
  #   depends_on:
  #     - api_server
  #   volumes:
  #     - ./slack_bot:/app
  #   ports:
  #     - "3000:3000"
  chat:
    build:
      context: ./chat
    env_file: .env
    depends_on:
      - api_server
    volumes:
      - ./chat:/app
    ports:
      - "3000:3000"
  # benzinga_newsfeed_websockets:
  #   build:
  #     context: ./benzinga_newsfeed_websockets
  #   env_file: .env
  #   depends_on:
  #     - nats
  #     - news_simulator_benzinga
  #   volumes:
  #     - ./benzinga_newsfeed_websockets:/app
  finhub_newsfeed_websockets:
    build:
      context: ./finhub_newsfeed_websockets
    env_file: .env
    depends_on:
      - nats
      - news_simulator_finhub
    volumes:
      - ./finhub_newsfeed_websockets:/app
# volumes:
#   postgres_data:
